### ISSUE TITLE
Sandbox is forced in MTurk

### ISSUE THREAD

**Issue by EliasBcd** [oTree-org/HR#1]
Hi,
OTree HR does not seem to work out of the MTurk sandbox.
When trying to publish a HIT for real, it requires checking the sandbox, making it impossible to publish a real study on MTurk.
I am not proficient enough in django to pinpoint exactly where this comes from.

**Comment by oTree-org** [comment]
Thanks for reporting! It should be fixed now, can you pull and try again?

**Comment by EliasBcd** [comment]
That was fast! It is working now, thanks!
